EN_DEBUG: false
EN_VISUAL: false
EN_METRIC: true
SAVE_SEGMENTED_CLOUD: true

DENSITY:
  first: false
  enable: true
  radius: 0.075 #0.075
  threshold: 5 #5  

EUCLID:
  enable: false
  radius: 0.5
  min_size: 5

MODE: "hybrid" # "ratio", "module", "hybrid", "wofine", "wocoarse_ratio", "wocoarse_module", "wocoarse_hybrid"
NODE_LENGTH: 2
NODE_WIDTH: 0.15
SAC_THRESHOLD: 0.5 #optim 0.25
VOXEL_SIZE: 0.05 
CROP_SET: 0